default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timezone: Asia/Karachi

development:
  <<: *default
  database: lahore_diagnostic_center_development

test:
  <<: *default
  database: lahore_diagnostic_center_test

production:
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  database: lahore_diagnostic_center_production
  port: 5432
  host: 'localhost'