default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lahore_diagnostic_center_development

test:
  <<: *default
  database: lahore_diagnostic_center_test

production:
  <<: *default
  database: lahore_diagnostic_center_production
  username: lahore_diagnostic_center
  password: <%= ENV["LAHORE_DIAGNOSTIC_CENTER_DATABASE_PASSWORD"] %>
